### ISSUE TITLE
Get back St. Andral's Bones!

### ISSUE THREAD

**Issue by captaincainer** [DVDAGames/campaign-notes#19]
A thief has stolen and sold the bones to the Coffin Maker who is being coerced by some vampire spawn. Get the bones back at any cost!

**Comment by captaincainer** [comment]
The group saved the Coffin shop from a fire caused by the vampire spawn. They were also able to save the life of the Coffin Maker! While one vampire-spawn was killed, two fled, but two of Vallaki's Burgomaster's guards set chase. Two other guards have witnessed the heroic acts of the group. The group has informed the guards that the culprit of the theft was the group of vampires. 

The group now must deliver the bones back to the church

**Comment by ericrallen** [comment]
We did it!
